In [1]:
import numpy as np

In [2]:
# Creating Array
array = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]] ,dtype=int)

In [3]:
print(array)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
# Printing Dimension
print(array.ndim)

2


In [5]:
# Printing Shape
print(array.shape)

(4, 3)


In [6]:
# Length of array
print(len(array))

4


In [7]:
# Delete 4th row
array = np.delete(array,3,0) # this function return new array
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
# Reshaping array into single row
array2 = array.reshape(1,-1) # -1 means it will take 2nd Dimension automatically
print(array2)

[[1 2 3 4 5 6 7 8 9]]


In [9]:
# Reshaping array, back to 3X3 Matrix 
array3 = array2.reshape(3,3)
print(array3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
print(array)
# Printing 1st Row 2nd Column Value
print(array[0][1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
